### PR TITLE
Implementing ed25519ph

### PR DESCRIPTION
**Pull request by joaomatossilva**
Implementing Partial update Signatures using the Ed25519 Pre-Hash version.

I tried to follow the most that I could the current code style and design, but please review and let me know any changes you see fit.

Thank you

### CODE REVIEW

**Comment by joaomatossilva** [comment]
Hi @ektrah , can you have a look on this PR?

**Comment by ektrah** [comment]
Looks overall quite good, thank you very much!

As I understand it, Ed25519 and Ed25519ph are two separate algorithms. So, I don't think that the `Ed25519ph` class should be a sub-class of `Ed25519`. I've taken the liberty to separate them in your branch and made a few other minor improvements along 
the way.

Using the same struct `IncrementalSignature` for both signing and verification is both nifty and a bit error-prone. Nifty because it is identical except for the last step. Error-prone because the user has to pass in the algorithm of the key in the first step and the key itself in the last step. I think it would be better if the key was passed in at the first step. What do you think about making two structs out of this?

Could you also add the new features to the documentation?

**Comment by joaomatossilva** [comment]
Documentation updated. I was a bit confused with the `SignatureAlgorithm2`. Please review

**Comment by ektrah** [comment]
Looks very good, thank you!

I removed the `Algorithm` parameter from the `Initialize` method since the key already contains the algorithm, and made some minor improvements to the documentation.

Merging.

**Pull request merged**
