### PR TITLE
Implement XChaCha20Poly1305

### PR DESCRIPTION
**Pull request by dustinsoftware**
This is identical to ChaCha20Poly1305, just with a larger nonce size. Support already exists in libsodium for this cipher.

### CODE REVIEW

**Comment by dustinsoftware** [comment]
Hmm.. not sure why the Ubuntu build failed. Looks like the Appveyor build was fine.

**Comment by ektrah** [comment]
The first pull request &ndash; thank you very much!

XChaCha20-Poly1305 is an AEAD algorithm that seems to have some nice properties. But it's really obscure. There's no specification, no test vectors, nothing. For this reason, I'm hesitant to add it to the NSec portfolio; see https://github.com/briansmith/ring/issues/411 for a similar discussion.

I do recognize the need for compatibility with specs that have decided to build on it nevertheless, though. I'm therefore thinking about something like a "libsodium compatibility pack" that includes algorithms like this and XSalsa20-Poly1305 (https://github.com/ektrah/nsec/issues/2). But I don't have plans to work on that anytime soon.

Right now, I would accept this pull request only as experimental code that lives in the NSec repository but doesn't get included in releases. It would then later be moved into the compatibility pack.

**Comment by dustinsoftware** [comment]
Thanks for the reply. A compatibility pack would probably be fine. I'm interested in referencing it from another library I'm developing [here](https://github.com/dustinsoftware/Paseto.NET) which needs to use that algorithm.

Per the [libsodium docs](https://download.libsodium.org/doc/secret-key_cryptography/xchacha20-poly1305_construction.html) it looks like this is the recommended algorithm to use if you have the option to, so I'm curious if it will become less obscure over time.

> ... For this reason, and if interoperability with other libraries is not a concern, this is the recommended AEAD construction.

**Comment by ektrah** [comment]
OK, let's bring this into shape and merge it into the experimental code area. I've made a few changes to the base classes in the meantime; the easiest way to update this code is probably to revert the changes and start fresh: copy `src/Cryptography/ChaCha20Poly1305.cs` to `src/Experimental/Sodium/XChaCha20Poly1305.cs`, copy `src/Interop/Interop.ChaCha20Poly1305.cs` to `src/Interop/Interop.XChaCha20Poly1305.cs`, and replace all occurrences of `crypto_aead_chacha20poly1305` with `crypto_aead_xchacha20poly1305` in both files. Don't bother with tests for now; just add the class to `tests/Registry.cs` to get some basic sanity checking.

**Comment by ektrah** [comment]
Added to NSec.Experimental in dd9ec7573d5436532c239b3ccbaae8313b636544

**Comment by dustinsoftware** [comment]
Thanks! :)

**Pull request closed without merging**
