### PR TITLE
add ed25519 to x25519

### PR DESCRIPTION
**Pull request by p3root**

### CODE REVIEW

**Comment by ektrah** [comment]
The code looks mostly good, but the value is a bit unclear to me. What are the use cases for this?

**Comment by p3root** [comment]
Because I want to use the same key for signature and encryption.

https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by ektrah** [comment]
The libsodium page notes:

> If you can afford it, using distinct keys for signing and for encryption is still highly recommended.

I'd +1 this recommendation. Any reason why you cannot (derive) distinct keys for signing and encryption?

**Comment by p3root** [comment]
Actually I don't want to handle two key pairs. Would be an extreme overhead on my side.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by p3root** [comment]
I have checked it again, I need this function. I don't have the information about the x25519 public keys on the counterpart only the public key of ed25519 - therefore I could convert the ed25519 pub key back to the x25519 key.

**Comment by ektrah** [comment]
Do you have a link to a specification that you could share?

**Comment by p3root** [comment]
Nope, because I don't have a spec. I could tell you privately what I am doing. NDA doesn't allow me to publish it here.

**Comment by p3root** [comment]
What are your concerns about this PR? libsodium is supporting it as well, why don't nsec as well?

**Comment by ektrah** [comment]
One of the goals with NSec is to make it "easy to use", which basically means that it should be difficult for users to shoot themselves in the foot. If some cryptographic primitive comes with certain caveats, the primitive should ideally be exposed in a way that these are automatically handled by NSec and not the user (e.g., by having suitable static (type) checks or run-time checks in the API). If that's not possible, it might be better to not expose a primitive at all than to claim it's "easy to use" and let users shoot themselves in the foot. 

Converting Ed25519 keys to X25519 keys seems to be useful (which is why it's included in libsodium) but clearly comes with some caveats (which is why it's an "advanced" feature of libsodium and has this note). I need to better understand the caveats before I can claim the API is "easy to use" from a security point of view.

Does that make sense? 😃 

What I can offer at the moment is to include your additions in the NSec.Experimental package, if you update the pull request accordingly.

**Pull request closed without merging**
